//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceClient.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name message from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTestMessage", ReplyAction="*")]
        WebServiceClient.ServiceReference1.GetTestMessageResponse GetTestMessage(WebServiceClient.ServiceReference1.GetTestMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTestMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.GetTestMessageResponse> GetTestMessageAsync(WebServiceClient.ServiceReference1.GetTestMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestMessage", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference1.GetTestMessageRequestBody Body;
        
        public GetTestMessageRequest() {
        }
        
        public GetTestMessageRequest(WebServiceClient.ServiceReference1.GetTestMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTestMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public GetTestMessageRequestBody() {
        }
        
        public GetTestMessageRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServiceReference1.GetTestMessageResponseBody Body;
        
        public GetTestMessageResponse() {
        }
        
        public GetTestMessageResponse(WebServiceClient.ServiceReference1.GetTestMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTestMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTestMessageResult;
        
        public GetTestMessageResponseBody() {
        }
        
        public GetTestMessageResponseBody(string GetTestMessageResult) {
            this.GetTestMessageResult = GetTestMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServiceClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServiceClient.ServiceReference1.WebService1Soap>, WebServiceClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference1.HelloWorldResponse WebServiceClient.ServiceReference1.WebService1Soap.HelloWorld(WebServiceClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceClient.ServiceReference1.HelloWorldRequest inValue = new WebServiceClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.HelloWorldRequestBody();
            WebServiceClient.ServiceReference1.HelloWorldResponse retVal = ((WebServiceClient.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> WebServiceClient.ServiceReference1.WebService1Soap.HelloWorldAsync(WebServiceClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServiceClient.ServiceReference1.HelloWorldRequest inValue = new WebServiceClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.HelloWorldRequestBody();
            return ((WebServiceClient.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference1.GetTestMessageResponse WebServiceClient.ServiceReference1.WebService1Soap.GetTestMessage(WebServiceClient.ServiceReference1.GetTestMessageRequest request) {
            return base.Channel.GetTestMessage(request);
        }
        
        public string GetTestMessage(string message) {
            WebServiceClient.ServiceReference1.GetTestMessageRequest inValue = new WebServiceClient.ServiceReference1.GetTestMessageRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.GetTestMessageRequestBody();
            inValue.Body.message = message;
            WebServiceClient.ServiceReference1.GetTestMessageResponse retVal = ((WebServiceClient.ServiceReference1.WebService1Soap)(this)).GetTestMessage(inValue);
            return retVal.Body.GetTestMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.GetTestMessageResponse> WebServiceClient.ServiceReference1.WebService1Soap.GetTestMessageAsync(WebServiceClient.ServiceReference1.GetTestMessageRequest request) {
            return base.Channel.GetTestMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.GetTestMessageResponse> GetTestMessageAsync(string message) {
            WebServiceClient.ServiceReference1.GetTestMessageRequest inValue = new WebServiceClient.ServiceReference1.GetTestMessageRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.GetTestMessageRequestBody();
            inValue.Body.message = message;
            return ((WebServiceClient.ServiceReference1.WebService1Soap)(this)).GetTestMessageAsync(inValue);
        }
    }
}
